### ISSUE TITLE
projects-labels

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#2]
I can't center the h3 in the  <div class="project-label">

**Comment by gorazd** [comment]
Can you please edit your issue description. Also adding a link to the page in question will help.
Thank you.

**Comment by Jesande** [comment]
jajajaja sorry!

I can't center the H3 In the .project-container:

https://github.com/Jesande/jesande.github.io/blob/0562bffb7cef18c3551c950e3cb463e184183a8b/index.html#L52

**Comment by gorazd** [comment]
Thank you, no need for apologies.

Centering doesn't work because 40% for the left property always results in the same  place. To center like this you need to know the width of the child. Set the left property to 50% and detract half of the child item's width. 
If you know the width is 500px by using the calc() function this is possible:
```left: calc(50% - 250px);```

Why not try putting a container inside the `div.project-container` and use flexbox for centering.
If you don't want the title to be larger than x, put a `max-height: x;` directly on the text elements.

![Screenshot 2020-04-27 19 31 32](https://user-images.githubusercontent.com/192416/80402161-c72c7f00-88bd-11ea-87fa-f6b6e1c9fab7.png)

**Comment by Jesande** [comment]
good! 
I fixed, thank you!
